lsi: false
safe: true
source: python-fundamentals-tutorial/python-fundamentals-tutorial-/0-weclome.md
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
